name: "Build"

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Node 22"
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: "Install"
        run: |
          npm install

      - name: "Update Manifest Version"
        if: ${{ github.event_name == 'release' }}
        uses: cssnr/update-json-value-action@v1

      - name: "Build"
        run: |
          npm run build

      - name: "Upload to Actions"
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: web-ext-artifacts/

      - name: "Upload to Release"
        if: ${{ github.event_name == 'release' }}
        uses: svenstaro/upload-release-action@v2
        with:
          file: web-ext-artifacts/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

      - name: "Update Release Notes Action"
        if: ${{ github.event_name == 'release' }}
        continue-on-error: true
        uses: smashedr/update-release-notes-action@master
        with:
          type: generic

      - name: "Package Changelog Action"
        if: ${{ github.event_name == 'release' }}
        continue-on-error: true
        uses: cssnr/package-changelog-action@v1

      - name: "Send Failure Notification"
        if: ${{ failure() && github.event_name == 'release' }}
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
