name: "Lint"

on:
  workflow_dispatch:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: ${{ !contains(github.event.head_commit.message, '#nolint') }}

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Node 22"
        uses: actions/setup-node@v4
        with:
          node-version: 22
          #cache: npm

      - name: "Install"
        id: install
        run: |
          npm install

      - name: "ESLint"
        if: ${{ steps.install.outcome == 'success' }}
        run: |
          npm run lint

      - name: "Prettier"
        if: ${{ steps.install.outcome == 'success' }}
        run: |
          npm run prettier
